version: '3.9' # Updated version; you can also remove it as it's obsolete in newer Docker Compose versions.

services:
  rabbitmq:
    image: rabbitmq:3.12-management # Use the latest stable version with management plugin
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
